CREATE TABLE `b3_precos` (
                             `tipo_registro` varchar(2) CHARACTER SET latin1 DEFAULT NULL COMMENT 'TIPO DE REGISTRO',
                             `data_atual` date NOT NULL COMMENT 'DATA DO PREGÃO',
                             `cod_bdi` varchar(2) CHARACTER SET latin1 DEFAULT NULL COMMENT 'CÓDIGO BDI',
                             `cod_neg` varchar(12) CHARACTER SET latin1 NOT NULL COMMENT 'CÓDIGO DE NEGOCIAÇÃO DO PAPEL',
                             `tipo_merc` varchar(3) CHARACTER SET latin1 DEFAULT NULL COMMENT 'TIPO DE MERCADO',
                             `nome_res` varchar(20) CHARACTER SET latin1 DEFAULT NULL COMMENT 'NOME RESUMIDO DA EMPRESA EMISSORA DO PAPEL',
                             `especific_papel` varchar(11) CHARACTER SET latin1 DEFAULT NULL COMMENT 'ESPECIFICAÇÃO DO PAPEL',
                             `prazo` int(3) NOT NULL DEFAULT '0' COMMENT 'PRAZO EM DIAS DO MERCADO A TERMO',
                             `moeda` varchar(5) CHARACTER SET latin1 DEFAULT NULL COMMENT 'MOEDA DE REFERÊNCIA',
                             `preco_abertura` float NOT NULL COMMENT 'PREÇO DE ABERTURA DO PAPELMERCADO NO PREGÃO',
                             `preco_max` float DEFAULT NULL COMMENT 'PREÇO MÁXIMO DO PAPELMERCADO NO PREGÃO',
                             `prec_min` float DEFAULT NULL COMMENT 'PREÇO MÍNIMO DO PAPELMERCADO NO PREGÃO',
                             `preco_medio` float DEFAULT NULL COMMENT 'PREÇO MÉDIO DO PAPELMERCADO NO PREGÃO',
                             `prec_ult` float DEFAULT NULL COMMENT 'PREÇO DO ÚLTIMO NEGÓCIO DO PAPEL-MERCADO NO PREGÃO',
                             `prec_mel_oferta_comp` float DEFAULT NULL COMMENT 'PREÇO DA MELHOR OFERTA DE COMPRA DO PAPELMERCADO',
                             `prec_mel_oferta_venda` float DEFAULT NULL COMMENT 'PREÇO DA MELHOR OFERTA DE VENDA DO PAPELMERCADO',
                             `num_neg` int(11) DEFAULT NULL COMMENT 'NÚMERO DE NEGÓCIOS EFETUADOS COM O PAPEL- MERCADO NO PREGÃO',
                             `quant_total_tit` bigint(20) DEFAULT NULL COMMENT 'QUANTIDADE TOTAL DE TÍTULOS NEGOCIADOS NESTE PAPEL- MERCADO',
                             `vol_total` bigint(20) DEFAULT NULL COMMENT 'VOLUME TOTAL DE TÍTULOS NEGOCIADOS NESTE PAPEL- MERCADO',
                             `preco_merc_opcoes` float DEFAULT NULL COMMENT 'PREÇO DE EXERCÍCIO PARA O MERCADO DE OPÇÕES OU VALOR DO CONTRATO PARA O MERCADO DE TERMO SECUNDÁRIO',
                             `ind_preco_correcoes` varchar(1) CHARACTER SET latin1 DEFAULT NULL COMMENT 'INDICADOR DE CORREÇÃO DE PREÇOS DE EXERCÍCIOS OU VALORES DE CONTRATO PARA OS MERCADOS DE OPÇÕES OU TERMO SECUNDÁRIO',
                             `data_venci_termo` date DEFAULT NULL COMMENT 'DATA DO VENCIMENTO PARA OS MERCADOS DE OPÇÕES OU TERMO SECUNDÁRIO',
                             `fat_cotacao` int(11) DEFAULT NULL COMMENT 'FATOR DE COTAÇÃO DO PAPEL',
                             `pto_exe` bigint(20) DEFAULT NULL COMMENT 'PREÇO DE EXERCÍCIO EM PONTOS PARA OPÇÕES REFERENCIADAS EM DÓLAR OU VALOR DE CONTRATO EM PONTOS PARA TERMO SECUNDÁRIO',
                             `cod_isin` varchar(12) CHARACTER SET latin1 NOT NULL COMMENT 'CÓDIGO DO PAPEL NO SISTEMA ISIN OU CÓDIGO INTERNO DO PAPEL',
                             `num_dis` int(11) DEFAULT NULL COMMENT 'NÚMERO DE DISTRIBUIÇÃO DO PAPEL',
                             PRIMARY KEY (`data_atual`,`cod_neg`,`cod_isin`,`prazo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8